apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-backend
  labels:
    app: saas-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saas-backend
  template:
    metadata:
      labels:
        app: saas-backend
    spec:
      containers:
        - name: backend
          # In a real environment, you'd replace 'latest' with a specific image tag using CI/CD.
          image: 569758639273.dkr.ecr.us-east-1.amazonaws.com/saas-backend:latest
          ports:
            - containerPort: 8080
          env:
            # Connecting to the database - this will point to the new RDS or Azure instance
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: saas-db-secret
                  key: database_url
            - name: NODE_ENV
              value: production
            # Connection to Keycloak instance
            - name: KEYCLOAK_URL
              value: http://saas-keycloak:8080/auth
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
---
apiVersion: v1
kind: Service
metadata:
  name: saas-backend
spec:
  selector:
    app: saas-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
