apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-ssm-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        jwt:
          # This maps back to the iam_role_for_service_accounts we created in eks.tf
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: saas-auth-sync
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: saas-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: keycloak_admin_password
      remoteRef:
        key: /saas/keycloak/admin-password
    # In a fully managed setup, you might also store 'admin' in SSM
    - secretKey: keycloak_admin
      remoteRef:
        key: /saas/keycloak/admin-user
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: saas-db-sync
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: saas-db-secret
    creationPolicy: Owner
  data:
    - secretKey: database_password
      remoteRef:
        key: /saas/database/password
    - secretKey: database_url
      remoteRef:
        key: /saas/database/url
    - secretKey: database_jdbc_url
      remoteRef:
        key: /saas/database/jdbc-url
