apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: saas-db-sync
  namespace: external-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: saas-db-secret
    creationPolicy: Owner
  data:
    - secretKey: database_password
      remoteRef:
        key: /saas/production/database/password
    - secretKey: database_url
      remoteRef:
        key: /saas/production/database/url
    - secretKey: database_jdbc_url
      remoteRef:
        key: /saas/production/database/jdbc-url
